[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contracts = "WvogQBTW3fvNABvsFk4nB6VvNLLNpEMP7rTe94zdwZH"

[programs.devnet]
contracts = "WvogQBTW3fvNABvsFk4nB6VvNLLNpEMP7rTe94zdwZH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
initialize = "ts-node scripts/initialize.ts"
